Repository hanghae-plus/front_2nd, pull requests merged in 2024-06, with the labels that each got.

#66 2주차 과제 제출 - 서준환
  packages/assignment-2/.eslintrc.cjs
  packages/assignment-2/.gitignore
  packages/assignment-2/package.json
  packages/assignment-2/src/advanced/__tests__/advanced.test.js
  packages/assignment-2/src/advanced/__tests__/advanced.test.jsx
  packages/assignment-2/src/advanced/advanced.js
  packages/assignment-2/src/advanced/advanced.jsx
  packages/assignment-2/src/basic/__tests__/basic.test.js
  packages/assignment-2/src/basic/basic.js
  packages/assignment-2/src/setupTests.ts
  packages/assignment-2/src/vite-env.d.ts
  packages/assignment-2/tsconfig.json
  packages/assignment-2/vitest.config.ts
  pnpm-lock.yaml
Labels: 10조

#84 2주차 과제 제출- 양혜원
  package.json
  packages/assignment-2/.eslintrc.cjs
  packages/assignment-2/.gitignore
  packages/assignment-2/package.json
  packages/assignment-2/src/advanced/__tests__/advanced.test.jsx
  packages/assignment-2/src/advanced/advanced.jsx
  packages/assignment-2/src/basic/__tests__/basic.test.js
  packages/assignment-2/src/basic/basic.js
  packages/assignment-2/src/setupTests.ts
  packages/assignment-2/src/vite-env.d.ts
  packages/assignment-2/tsconfig.json
  packages/assignment-2/vitest.config.ts
  pnpm-lock.yaml
Labels: 5조

#85 2주차 과제 제출 - 정수진
  packages/assignment-2/.eslintrc.cjs
  packages/assignment-2/.gitignore
  packages/assignment-2/package.json
  packages/assignment-2/src/advanced/__tests__/advanced.test.jsx
  packages/assignment-2/src/advanced/advanced.jsx
  packages/assignment-2/src/basic/__tests__/basic.test.js
  packages/assignment-2/src/basic/basic.js
  packages/assignment-2/src/setupTests.ts
  packages/assignment-2/src/vite-env.d.ts
  packages/assignment-2/tsconfig.json
  packages/assignment-2/vitest.config.ts
  pnpm-lock.yaml
Labels: 5조

#86 2주차 과제 제출 - 신정규
  packages/assignment-2/.eslintrc.cjs
  packages/assignment-2/.gitignore
  packages/assignment-2/package.json
  packages/assignment-2/src/advanced/__tests__/advanced.test.jsx
  packages/assignment-2/src/advanced/advanced.jsx
  packages/assignment-2/src/basic/__tests__/basic.test.js
  packages/assignment-2/src/basic/basic.js
  packages/assignment-2/src/setupTests.ts
  packages/assignment-2/src/vite-env.d.ts
  packages/assignment-2/tsconfig.json
  packages/assignment-2/vitest.config.ts
  pnpm-lock.yaml
Labels: 10조

#88 2주차 과제제출 - 김초원
  packages/assignment-2/.eslintrc.cjs
  packages/assignment-2/.gitignore
  packages/assignment-2/package.json
  packages/assignment-2/src/advanced/__tests__/advanced.test.jsx
  packages/assignment-2/src/advanced/advanced.jsx
  packages/assignment-2/src/basic/__tests__/basic.test.js
  packages/assignment-2/src/basic/basic.js
  packages/assignment-2/src/setupTests.ts
  packages/assignment-2/src/vite-env.d.ts
  packages/assignment-2/tsconfig.json
  packages/assignment-2/vitest.config.ts
  packages/assignment-3/.eslintrc.cjs
  packages/assignment-3/.gitignore
  packages/assignment-3/package.json
  packages/assignment-3/src/advanced/__tests__/hooks.test.js
  packages/assignment-3/src/advanced/hooks.js
  packages/assignment-3/src/basic/MyReact.js
  packages/assignment-3/src/basic/__tests__/MyReact.test.js
  packages/assignment-3/src/basic/__tests__/hooks.test.js
  packages/assignment-3/src/basic/__tests__/render.test.js
  packages/assignment-3/src/basic/hooks.js
  packages/assignment-3/src/basic/render.js
  packages/assignment-3/src/vite-env.d.ts
  packages/assignment-3/tsconfig.json
  packages/assignment-3/vitest.config.ts
  pnpm-lock.yaml
Labels: 4조

#92 2주차 과제 제출 - 심승혁
  packages/assignment-2/.eslintrc.cjs
  packages/assignment-2/.gitignore
  packages/assignment-2/package.json
  packages/assignment-2/src/advanced/__tests__/advanced.test.jsx
  packages/assignment-2/src/advanced/advanced.jsx
  packages/assignment-2/src/basic/__tests__/basic.test.js
  packages/assignment-2/src/basic/basic.js
  packages/assignment-2/src/setupTests.ts
  packages/assignment-2/src/vite-env.d.ts
  packages/assignment-2/tsconfig.json
  packages/assignment-2/vitest.config.ts
  packages/assignment-3/.eslintrc.cjs
  packages/assignment-3/.gitignore
  packages/assignment-3/package.json
  packages/assignment-3/src/advanced/__tests__/hooks.test.js
  packages/assignment-3/src/advanced/hooks.js
  packages/assignment-3/src/basic/MyReact.js
  packages/assignment-3/src/basic/__tests__/MyReact.test.js
  packages/assignment-3/src/basic/__tests__/hooks.test.js
  packages/assignment-3/src/basic/__tests__/render.test.js
  packages/assignment-3/src/basic/hooks.js
  packages/assignment-3/src/basic/render.js
  packages/assignment-3/src/vite-env.d.ts
  packages/assignment-3/tsconfig.json
  packages/assignment-3/vitest.config.ts
  pnpm-lock.yaml
Labels: 4조

#103 [형예은] 2주차 과제 제출
  packages/assignment-2/.eslintrc.cjs
  packages/assignment-2/.gitignore
  packages/assignment-2/package.json
  packages/assignment-2/src/advanced/__tests__/advanced.test.jsx
  packages/assignment-2/src/advanced/advanced.jsx
  packages/assignment-2/src/basic/__tests__/basic.test.js
  packages/assignment-2/src/basic/basic.js
  packages/assignment-2/src/setupTests.ts
  packages/assignment-2/src/vite-env.d.ts
  packages/assignment-2/tsconfig.json
  packages/assignment-2/vitest.config.ts
  packages/assignment-3/.eslintrc.cjs
  packages/assignment-3/.gitignore
  packages/assignment-3/package.json
  packages/assignment-3/src/advanced/__tests__/hooks.test.js
  packages/assignment-3/src/advanced/hooks.js
  packages/assignment-3/src/basic/MyReact.js
  packages/assignment-3/src/basic/__tests__/MyReact.test.js
  packages/assignment-3/src/basic/__tests__/hooks.test.js
  packages/assignment-3/src/basic/__tests__/render.test.js
  packages/assignment-3/src/basic/hooks.js
  packages/assignment-3/src/basic/render.js
  packages/assignment-3/src/vite-env.d.ts
  packages/assignment-3/tsconfig.json
  packages/assignment-3/vitest.config.ts
  pnpm-lock.yaml
Labels: 4조
