Repository hanghae-plus/front_2nd, pull requests merged in 2024-08, with the labels that each got.

#458 7주차 과제 제출 - 이충현
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/.prettierrc
  packages/assignment-7/eslintrc.json
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/basic/__tests__/integration.test.tsx
  packages/assignment-7/src/basic/__tests__/mockApiHandlers.ts
  packages/assignment-7/src/basic/__tests__/mockData.ts
  packages/assignment-7/src/basic/__tests__/mockEvents.ts
  packages/assignment-7/src/basic/__tests__/units.test.tsx
  packages/assignment-7/src/components/CalenderView.tsx
  packages/assignment-7/src/components/EventForm.tsx
  packages/assignment-7/src/components/EventList.tsx
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/utils/dateUtils.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/temp/tests__/units.test.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 1조

#462 7주차 과제 제출 - 정수진
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/hooks.test.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/constants.ts
  packages/assignment-7/src/hooks/index.ts
  packages/assignment-7/src/hooks/useEventForm.ts
  packages/assignment-7/src/hooks/useEvents.ts
  packages/assignment-7/src/hooks/useNotification.ts
  packages/assignment-7/src/hooks/useView.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mocks/mockApiHandlers.ts
  packages/assignment-7/src/mocks/mockData.ts
  packages/assignment-7/src/mocks/mockFetchHolidays.ts
  packages/assignment-7/src/types.ts
  packages/assignment-7/src/utils/dateUtils.ts
  packages/assignment-7/src/utils/eventUtils.ts
  packages/assignment-7/src/utils/validationTools.ts
  pnpm-lock.yaml
Labels: 5조

#463 7주차 과제 제출 - 유시온
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/MonthCalendarView/index.tsx
  packages/assignment-7/src/components/WeekCalendarView/index.tsx
  packages/assignment-7/src/hooks/useGetEvents.ts
  packages/assignment-7/src/hooks/useGetFilteredEvents.ts
  packages/assignment-7/src/hooks/useGetHolidays.ts
  packages/assignment-7/src/hooks/useNotifiedEvents.ts
  packages/assignment-7/src/mockApiHandlers.ts
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/shared/categories.ts
  packages/assignment-7/src/shared/notification.ts
  packages/assignment-7/src/shared/weekdays.ts
  packages/assignment-7/src/types/event.ts
  packages/assignment-7/src/utils/date.spec.ts
  packages/assignment-7/src/utils/date.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 9조

#465 7주차 과제 제출 - 박지한
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/Scheduler/index.tsx
  packages/assignment-7/src/Scheduler/useScheduler.ts
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/testutils.ts
  packages/assignment-7/src/__tests__/unitTests/hooks/useCalendarView.test.ts
  packages/assignment-7/src/__tests__/unitTests/hooks/useEventForm.test.ts
  packages/assignment-7/src/__tests__/unitTests/hooks/useEventNotifications.test.ts
  packages/assignment-7/src/__tests__/unitTests/hooks/useEventSearch.test.ts
  packages/assignment-7/src/__tests__/unitTests/hooks/useOverlappingEvents.test.ts
  packages/assignment-7/src/__tests__/unitTests/utils.test.ts
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/CalendarView/MonthView/index.tsx
  packages/assignment-7/src/components/CalendarView/WeekView/index.tsx
  packages/assignment-7/src/components/CalendarView/index.tsx
  packages/assignment-7/src/components/EventForm/index.tsx
  packages/assignment-7/src/components/EventList/index.tsx
  packages/assignment-7/src/components/NotificationAlert/index.tsx
  packages/assignment-7/src/components/OverlappingAlert/index.tsx
  packages/assignment-7/src/contants.ts
  packages/assignment-7/src/hooks/useCalendarView.ts
  packages/assignment-7/src/hooks/useEventForm.ts
  packages/assignment-7/src/hooks/useEventManager.ts
  packages/assignment-7/src/hooks/useEventNotifications.ts
  packages/assignment-7/src/hooks/useEventSearch.ts
  packages/assignment-7/src/hooks/useOverlappingEvents.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mocks/mockServiceWorker/browser.ts
  packages/assignment-7/src/mocks/mockServiceWorker/handlers.ts
  packages/assignment-7/src/mocks/mockdata/events.ts
  packages/assignment-7/src/types.ts
  packages/assignment-7/src/utils/formatMonth.ts
  packages/assignment-7/src/utils/formatWeek.ts
  packages/assignment-7/src/utils/getDaysInMonth.ts
  packages/assignment-7/src/utils/getWeekDates.ts
  packages/assignment-7/src/utils/isDateInRange.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/vite.config.ts
Labels: 5조

#466 7주차 과제 제출 - 오현석
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/AlertView.tsx
  packages/assignment-7/src/components/EventDetailView.tsx
  packages/assignment-7/src/components/EventForm.tsx
  packages/assignment-7/src/components/MonthView.tsx
  packages/assignment-7/src/components/NotificationView.tsx
  packages/assignment-7/src/components/ViewBox.tsx
  packages/assignment-7/src/components/WeekView.tsx
  packages/assignment-7/src/constants/constants.ts
  packages/assignment-7/src/lib/services/mockData.ts
  packages/assignment-7/src/lib/services/mockHandlers.ts
  packages/assignment-7/src/lib/utils/date.ts
  packages/assignment-7/src/lib/utils/dateFormat.ts
  packages/assignment-7/src/lib/utils/validate.ts
  packages/assignment-7/src/types/types.ts
Labels: 6조

#469 7주차 과제 제출 - 최현우
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  packages/assignment-7/mock/handler.ts
  packages/assignment-7/mock/worker.ts
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/event/calendar/EventCalendar.tsx
  packages/assignment-7/src/components/event/collection/EventList.tsx
  packages/assignment-7/src/components/event/collection/test/EventList.test.tsx
  packages/assignment-7/src/components/event/form/EventForm.tsx
  packages/assignment-7/src/components/event/form/hooks/test/useEventForm.test.ts
  packages/assignment-7/src/components/event/form/hooks/useEventForm.ts
  packages/assignment-7/src/components/event/hooks/test/useClosure.test.ts
  packages/assignment-7/src/components/event/hooks/test/useFilterEvent.test.ts
  packages/assignment-7/src/components/event/hooks/test/useGetEvent.test.ts
  packages/assignment-7/src/components/event/hooks/useClosure.ts
  packages/assignment-7/src/components/event/hooks/useDeleteEvent.ts
  packages/assignment-7/src/components/event/hooks/useFilterEvent.ts
  packages/assignment-7/src/components/event/hooks/useGetEvent.ts
  packages/assignment-7/src/components/event/hooks/useSaveEvent.ts
  packages/assignment-7/src/components/event/notification/EventNotification.tsx
  packages/assignment-7/src/components/event/notification/hooks/useNotification.ts
  packages/assignment-7/src/components/event/panel/EventPanel.tsx
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/types/types.ts
  packages/assignment-7/src/utils/date-utils.ts
  packages/assignment-7/src/utils/test/units.test.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/vite.config.ts
  packages/assignment-7/vitest.setup.ts
  pnpm-lock.yaml
Labels: 7조

#473 7주차 과제 제출 - 신승준
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package.json
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mocks/browser.ts
  packages/assignment-7/src/mocks/handlers.ts
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/types/event.ts
  packages/assignment-7/src/utils/date.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 11조

#475 7주차 과제 제출 - 전창기
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  .prettierrc
  eslint.config.mjs
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package-lock.json
  package.json
  packages/assignment-1/src/advanced/useMyRef.ts
  packages/assignment-4/src/advanced/templates.ts
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/prettier.config.cjs
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/shared/model/dateTimeUtils.test.ts
  packages/assignment-7/src/shared/model/dateTimeUtils.ts
  packages/assignment-7/src/utils/test/handlers.ts
  packages/assignment-7/src/utils/test/server.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  yarn.lock
Labels: 12조

#476 7주차 과제 제출 - 이예빈
  packages/assignment-7/mock/handler.ts
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/utils.ts
  packages/assignment-7/tsconfig.app.json
  pnpm-lock.yaml
Labels: 13조

#479 7주차 과제 제출 - 서준환
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package.json
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mocks/handlers.ts
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/utils/date.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 10조

#480 7주차 과제 제출 - 서동균
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package-lock.json
  package.json
  packages/assignment-6/assignment-6-ci.yaml
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/mockApiHandlers.ts
  packages/assignment-7/src/__tests__/mockEvents.ts
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/alert/AlertConfirm.tsx
  packages/assignment-7/src/components/alert/AlertNotice.tsx
  packages/assignment-7/src/components/calendar/Calendar.tsx
  packages/assignment-7/src/components/calendar/MonthCalendar.tsx
  packages/assignment-7/src/components/calendar/WeekCalendar.tsx
  packages/assignment-7/src/components/form/EventForm.tsx
  packages/assignment-7/src/components/list/EventList.tsx
  packages/assignment-7/src/constants/constants.ts
  packages/assignment-7/src/hook/useEvents.ts
  packages/assignment-7/src/hook/useForm.ts
  packages/assignment-7/src/hook/useNotice.ts
  packages/assignment-7/src/hook/useValidateTime.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/types/types.ts
  packages/assignment-7/src/utils/utilsFunc.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 1조

#483 7주차 과제 제출 - 최서현
  .DS_Store
  packages/.DS_Store
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__mock__/handlers/mockEventApiHandlers.ts
  packages/assignment-7/src/__mock__/handlers/mockHolidayApiHandlers.ts
  packages/assignment-7/src/__mock__/mockData.ts
  packages/assignment-7/src/__tests__/eventform.test.tsx
  packages/assignment-7/src/__tests__/eventsearch.test.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/monthview.test.tsx
  packages/assignment-7/src/__tests__/notificationlist.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/__tests__/weekview.test.tsx
  packages/assignment-7/src/components/EventForm.tsx
  packages/assignment-7/src/components/EventSearch.tsx
  packages/assignment-7/src/components/NotificationList.tsx
  packages/assignment-7/src/components/calendar/MonthView.tsx
  packages/assignment-7/src/components/calendar/WeekView.tsx
  packages/assignment-7/src/constants/constants.ts
  packages/assignment-7/src/hooks/index.ts
  packages/assignment-7/src/hooks/useCalendarSearch.ts
  packages/assignment-7/src/hooks/useEventCRUD.ts
  packages/assignment-7/src/hooks/useEventForm.ts
  packages/assignment-7/src/hooks/useEventNotifications.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/types/types.ts
  packages/assignment-7/src/utils/eventUtils.ts
  packages/assignment-7/src/utils/testUtils.ts
  packages/assignment-7/src/utils/utils.ts
  packages/assignment-7/tsconfig.app.json
  pnpm-lock.yaml
Labels: 6조

#485 7주차 과제 제출 - 김혜성
  .github/workflows/assignment-6-ci.yml
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/common/FormCheckbox.tsx
  packages/assignment-7/src/components/common/FormField.tsx
  packages/assignment-7/src/components/common/FormSelect.tsx
  packages/assignment-7/src/hooks/useEvents.tsx
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mockApiHandlers.ts
  packages/assignment-7/src/utils/formatMonth.ts
  packages/assignment-7/src/utils/formatWeek.ts
  packages/assignment-7/src/utils/getDatysInMonth.ts
  packages/assignment-7/src/utils/getWeekDates.ts
  pnpm-lock.yaml
Labels: 8조

#486 7주차 과제 제출 - 김초원
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package.json
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/EventAlert.tsx
  packages/assignment-7/src/components/EventDisplay.tsx
  packages/assignment-7/src/components/EventForm.tsx
  packages/assignment-7/src/components/EventList.tsx
  packages/assignment-7/src/components/EventManager.tsx
  packages/assignment-7/src/components/EventNotification.tsx
  packages/assignment-7/src/components/MonthView.tsx
  packages/assignment-7/src/components/ViewSelector.tsx
  packages/assignment-7/src/components/WeekView.tsx
  packages/assignment-7/src/dummys.ts
  packages/assignment-7/src/hooks/useEventForm.ts
  packages/assignment-7/src/hooks/useEvents.ts
  packages/assignment-7/src/hooks/useFetchEvents.ts
  packages/assignment-7/src/hooks/useFetchHolidays.ts
  packages/assignment-7/src/hooks/useNotificaiton.ts
  packages/assignment-7/src/hooks/useValidation.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mockApiHandlers.ts
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/types.ts
  packages/assignment-7/src/utils.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 4조

#489 7주차 과제 - 신해지
  package.json
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mockApiHandlers.ts
  packages/assignment-7/src/utils.tsx
  pnpm-lock.yaml
Labels: 8조

#491 7주차 과제 제출 - 안주홍
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package.json
  packages/assignment-6/coverage/coverage-final.json
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/advanced.test.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/components/EventForm.tsx
  packages/assignment-7/src/components/MonthView.tsx
  packages/assignment-7/src/components/WeekView.tsx
  packages/assignment-7/src/hooks/useEvent.ts
  packages/assignment-7/src/hooks/useEventManagement.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mockCalendarApiHandler.ts
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/testFn/dateFn.ts
  packages/assignment-7/src/testFn/eventFn.ts
  packages/assignment-7/src/types/type.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 12조

#493 7주차 과제 제출 - 형예은
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/component.test.tsx
  packages/assignment-7/src/__tests__/customhook.test.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/__tests__/util.test.ts
  packages/assignment-7/src/components/AlertModal.tsx
  packages/assignment-7/src/components/CalendarView.tsx
  packages/assignment-7/src/components/EventForm.tsx
  packages/assignment-7/src/components/EventList.tsx
  packages/assignment-7/src/components/EventListItem.tsx
  packages/assignment-7/src/components/MonthView.tsx
  packages/assignment-7/src/components/NotificationAlert.tsx
  packages/assignment-7/src/components/WeekView.tsx
  packages/assignment-7/src/hooks/useEventForm.ts
  packages/assignment-7/src/magicnumbers.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mockApiHandlers.ts
  packages/assignment-7/src/types.ts
  packages/assignment-7/src/utils.ts
  pnpm-lock.yaml
Labels: 4조

#494 7주차 과제 제출 - 박지연
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__mocks__/handlers.ts
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/utils.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 1조

#495 7주차 과제 제출 - 박동현
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package.json
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/basic/App.tsx
  packages/assignment-7/src/basic/__tests__/integration.test.tsx
  packages/assignment-7/src/basic/__tests__/units.test.ts
  packages/assignment-7/src/basic/index.html
  packages/assignment-7/src/basic/main.tsx
  packages/assignment-7/src/basic/mockApiHandlers.ts
  packages/assignment-7/src/basic/setupTests.ts
  packages/assignment-7/src/basic/utils/index.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.advanced.ts
  packages/assignment-7/vite.config.basic.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 9조

#496 7주차 과제 제출 - 이민영
  .github/labeler-config.yml
  .github/workflows/assignment-7-ci.yml
  examples/todo-list-with-msw/.eslintrc.cjs
  examples/todo-list-with-msw/.gitignore
  examples/todo-list-with-msw/index.html
  examples/todo-list-with-msw/package.json
  examples/todo-list-with-msw/public/mockServiceWorker.js
  examples/todo-list-with-msw/src/App.test.tsx
  examples/todo-list-with-msw/src/App.tsx
  examples/todo-list-with-msw/src/main.tsx
  examples/todo-list-with-msw/src/mockApiHandlers.ts
  examples/todo-list-with-msw/src/setupTests.ts
  examples/todo-list-with-msw/src/vite-env.d.ts
  examples/todo-list-with-msw/tsconfig.app.json
  examples/todo-list-with-msw/tsconfig.json
  examples/todo-list-with-msw/tsconfig.node.json
  examples/todo-list-with-msw/vite.config.ts
  package.json
  packages/assignment-7/.eslintrc.cjs
  packages/assignment-7/.gitignore
  packages/assignment-7/index.html
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/public/vite.svg
  packages/assignment-7/server.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mockApiHandlers.ts
  packages/assignment-7/src/setupTests.ts
  packages/assignment-7/src/vite-env.d.ts
  packages/assignment-7/tsconfig.app.json
  packages/assignment-7/tsconfig.json
  packages/assignment-7/tsconfig.node.json
  packages/assignment-7/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 6조

#477 7주차 과제 제출 - 모신영
  packages/assignment-7/package.json
  packages/assignment-7/public/mockServiceWorker.js
  packages/assignment-7/src/App.tsx
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-7/src/__tests__/units.test.ts
  packages/assignment-7/src/main.tsx
  packages/assignment-7/src/mockApiHandlers.ts
  packages/assignment-7/src/utils.tsx
  pnpm-lock.yaml
Labels: 8조

#506 8주차 과제 sync - 서준환
  .github/workflows/assignment-8-ci.yml
  packages/assignment-8/.eslintrc.cjs
  packages/assignment-8/.gitignore
  packages/assignment-8/index.html
  packages/assignment-8/package.json
  packages/assignment-8/public/vite.svg
  packages/assignment-8/server.js
  packages/assignment-8/src/App.tsx
  packages/assignment-8/src/__tests__/createMockServer.ts
  packages/assignment-8/src/__tests__/hooks.test.ts
  packages/assignment-8/src/__tests__/integration.test.tsx
  packages/assignment-8/src/__tests__/units.test.ts
  packages/assignment-8/src/apis/fetchHolidays.ts
  packages/assignment-8/src/hooks/useCalendarView.ts
  packages/assignment-8/src/hooks/useEventForm.ts
  packages/assignment-8/src/hooks/useEventOperations.ts
  packages/assignment-8/src/hooks/useNotifications.ts
  packages/assignment-8/src/hooks/useSearch.ts
  packages/assignment-8/src/main.tsx
  packages/assignment-8/src/setupTests.ts
  packages/assignment-8/src/types.ts
  packages/assignment-8/src/utils/dateUtils.ts
  packages/assignment-8/src/utils/eventOverlap.ts
  packages/assignment-8/src/utils/eventUtils.ts
  packages/assignment-8/src/utils/notificationUtils.ts
  packages/assignment-8/src/utils/timeValidation.ts
  packages/assignment-8/src/vite-env.d.ts
  packages/assignment-8/tsconfig.app.json
  packages/assignment-8/tsconfig.json
  packages/assignment-8/tsconfig.node.json
  packages/assignment-8/vite.config.ts
  pnpm-lock.yaml
Labels: 10조

#530 8주차 과제 업데이트 - 정수진
  .github/pull_request_template.md
  .github/workflows/assignment-8-ci.yml
  packages/assignment-8/.eslintrc.cjs
  packages/assignment-8/.gitignore
  packages/assignment-8/index.html
  packages/assignment-8/package.json
  packages/assignment-8/public/vite.svg
  packages/assignment-8/server.js
  packages/assignment-8/src/App.tsx
  packages/assignment-8/src/main.tsx
  packages/assignment-8/src/setupTests.ts
  packages/assignment-8/src/vite-env.d.ts
  packages/assignment-8/tsconfig.app.json
  packages/assignment-8/tsconfig.json
  packages/assignment-8/tsconfig.node.json
  packages/assignment-8/vite.config.ts
  pnpm-lock.yaml
Labels: 5조

#518 8주차 과제 제출 - 오현석
  packages/assignment-8/src/App.tsx
  packages/assignment-8/src/__tests__/integration.test.tsx
  packages/assignment-8/src/__tests__/scenario.test.md
  packages/assignment-8/src/components/AlertView.tsx
  packages/assignment-8/src/components/EventDetailView.tsx
  packages/assignment-8/src/components/EventForm.tsx
  packages/assignment-8/src/components/MonthView.tsx
  packages/assignment-8/src/components/NotificationView.tsx
  packages/assignment-8/src/components/ViewBox.tsx
  packages/assignment-8/src/components/WeekView.tsx
  packages/assignment-8/src/constants/constants.ts
  packages/assignment-8/src/hooks/useFilteredEvents.ts
  packages/assignment-8/src/lib/services/mockData.ts
  packages/assignment-8/src/lib/services/mockHandlers.ts
  packages/assignment-8/src/lib/utils/date.ts
  packages/assignment-8/src/lib/utils/dateFormat.ts
  packages/assignment-8/src/types/types.ts
  packages/assignment-8/test_strategy.md
Labels: 6조

#520 8주차 과제 제출 - 김초원
  packages/assignment-8/src/App.tsx
  packages/assignment-8/src/__test__/integration.test.tsx
  packages/assignment-8/src/hooks/useEventOperations.ts
  packages/assignment-8/src/utils/dateUtils.ts
Labels: 4조

#527 8주차 과제 제출 - 박지한
  packages/assignment-7/src/__tests__/integration.test.tsx
  packages/assignment-8/src/Scheduler/index.tsx
  packages/assignment-8/src/Scheduler/useScheduler.ts
  packages/assignment-8/src/__tests__/integrationTests/eventRepetition.test.tsx
  packages/assignment-8/src/__tests__/integrationTests/integration.test.tsx
  packages/assignment-8/src/__tests__/scenarios/scenarioA.test.ts
  packages/assignment-8/src/__tests__/testModules.ts
  packages/assignment-8/src/__tests__/testStrategy.md
  packages/assignment-8/src/__tests__/testUtils.ts
  packages/assignment-8/src/__tests__/unitTests/hooks/useEventNotifications.test.ts
  packages/assignment-8/src/__tests__/unitTests/utils/getEventGeneratedRepeatChildren.test.ts
  packages/assignment-8/src/__tests__/unitTests/utils/utils.test.ts
  packages/assignment-8/src/components/CalendarView/MonthView/index.tsx
  packages/assignment-8/src/components/CalendarView/WeekView/index.tsx
  packages/assignment-8/src/components/EventForm/index.tsx
  packages/assignment-8/src/components/EventList/EventListItem/index.tsx
  packages/assignment-8/src/components/EventList/index.tsx
  packages/assignment-8/src/components/RepeatEventRemoveAlert/index.tsx
  packages/assignment-8/src/hooks/useEventManager.ts
  packages/assignment-8/src/hooks/useEventSearch.ts
  packages/assignment-8/src/main.tsx
  packages/assignment-8/src/mocks/mockdata/events.ts
  packages/assignment-8/src/types.ts
  packages/assignment-8/src/utils/getEventGeneratedRepeatChildren.ts
  packages/assignment-8/vite.config.ts
Labels: 5조

#532 8주차 과제 제출 - 정수진
  packages/assignment-8/package.json
  packages/assignment-8/public/mockServiceWorker.js
  packages/assignment-8/src/App.tsx
  packages/assignment-8/src/__test__/basic.test.tsx
  packages/assignment-8/src/components/EventAddOrUpdate/index.tsx
  packages/assignment-8/src/components/EventSearch/index.tsx
  packages/assignment-8/src/components/EventView/MonthView/index.tsx
  packages/assignment-8/src/components/EventView/WeekView/index.tsx
  packages/assignment-8/src/components/EventView/index.tsx
  packages/assignment-8/src/components/Notifications/index.tsx
  packages/assignment-8/src/components/OverlappingAlert/index.tsx
  packages/assignment-8/src/constants.ts
  packages/assignment-8/src/hooks/index.ts
  packages/assignment-8/src/hooks/useEventForm.ts
  packages/assignment-8/src/hooks/useEvents.ts
  packages/assignment-8/src/hooks/useNotification.ts
  packages/assignment-8/src/hooks/useSearch.ts
  packages/assignment-8/src/hooks/useView.ts
  packages/assignment-8/src/mocks/mockApiHandlers.ts
  packages/assignment-8/src/mocks/mockData.ts
  packages/assignment-8/src/mocks/mockFetchHolidays.ts
  packages/assignment-8/src/types.ts
  packages/assignment-8/src/utils/__tests__/units.test.ts
  packages/assignment-8/src/utils/dateUtils.ts
  packages/assignment-8/src/utils/eventUtils.ts
  packages/assignment-8/src/utils/validationTools.ts
Labels: 5조
